Add translation disclaimer to ru articles
effector/new-docs pull request #29
Opened 2023-04-03 22:56 UTC by ainursharaev

This MR adds `TranslationDisclaimer` component that appears on our `ru` documentation pages. 

This component aims to provide our Russian-speaking users with a clear and concise message about the accuracy of the translated documentation. By displaying this disclaimer message on our documentation pages, we hope to reduce confusion and ensure our users can access the most up-to-date and accurate information.

Closes EFX-120

2023-04-04 08:05 UTC, sergeysova requested changes

2023-04-04 08:05 UTC, sergeysova commented on src/components/TranslationDisclaimer.astro
> +            актуальной информации рекомендуем использовать оригинальную <a href={link} target="_blank">англоязычную
Are we need _blank here?

2023-04-04 08:05 UTC, sergeysova commented on src/pages/[lang]/[...slug].astro
> +import TranslationDisclaimor from "../../components/TranslationDisclaimer.astro";
```suggestion
import TranslationDisclaimer from "../../components/TranslationDisclaimer.astro";
```

2023-04-04 08:05 UTC, sergeysova commented on src/pages/[lang]/[...slug].astro
> +  {lang !== 'en' ? <TranslationDisclaimor link={`/en/${slug}`} /> : null}
```suggestion
  {lang !== SITE.defaultLanguage ? <TranslationDisclaimor link={`/${SITE.defaultLanguage}/${slug}`} /> : null}
```

2023-04-04 08:05 UTC, sergeysova commented on src/components/TranslationDisclaimer.astro
> +        <span class="admonition-title">Перевод поддерживается сообществом</span>
I suggest translating this content via `getTextLocalized`

2023-04-04 08:05 UTC, sergeysova commented on src/components/TranslationDisclaimer.astro
> +        <span class="admonition-title">Перевод поддерживается сообществом</span>
I think there will be more languages

2023-04-05 18:43 UTC, ainursharaev commented on src/components/TranslationDisclaimer.astro
> +            актуальной информации рекомендуем использовать оригинальную <a href={link} target="_blank">англоязычную
I don't think so, thanks for pointing out

2023-04-05 18:44 UTC, ainursharaev commented on src/pages/[lang]/[...slug].astro
> +import TranslationDisclaimor from "../../components/TranslationDisclaimer.astro";
Applied it, thanks!

2023-04-05 18:45 UTC, ainursharaev commented on src/pages/[lang]/[...slug].astro
> +  {lang !== 'en' ? <TranslationDisclaimor link={`/en/${slug}`} /> : null}
Totally make sense, added it

2023-04-05 18:58 UTC, ainursharaev commented on src/components/TranslationDisclaimer.astro
> +        <span class="admonition-title">Перевод поддерживается сообществом</span>
Added the texts to `translations`

2023-04-06 15:12 UTC, merged